### ISSUE TITLE
Easter Feat "Bunny Helpers" is missing and gets removed on import.

### ISSUE THREAD

**Issue by drseilzug** [dox4242/RG-tools#46]
The Event feat "bunny Helpers" is not present in the editor and importing an edited savefile will remove it from the feat list even if the original file had it.

**Comment by dox4242** [comment]
Until the next patch comes out (we're on 3.1.1.0 right now), the Bunny Helpers feat is bugged. This is a known issue. It's bugged because they forgot to put the ID variable in the feat. The game defaults the ID to 0, but since it doesn't even know what ID to look for, it won't appear when you import ANY kind of save file.
