### ISSUE TITLE
halloween event

### ISSUE THREAD

**Issue by mauroofcol** [dox4242/RG-tools#8]
when i edit a saved game, the seasonal event values, like pumkins mosters, and monster coins, resets to 0, by the way, thanks a lot for this tool

**Comment by weltandmelt** [comment]
i get something simmilar on my alt, it removes the monsterm byt i still have the bones, blood and ectoplasm and the puumpkin

**Comment by dox4242** [comment]
I think I encountered this issue when I was play testing. My spent resources on monster levels would reset to 0, but I'd have the resources I edited in. I think it's a fixable issue, but it would take me longer than the event to figure it out. Otherwise, just edit enough resources to buy back any lost monster levels.
